// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGheHUNRhYJhDOTsgxzzpx-tVlgEDVpc',
    appId: '1:357089760561:web:c95f9ea1834d1197724c10',
    messagingSenderId: '357089760561',
    projectId: 'shared-notes-app-2a464',
    authDomain: 'shared-notes-app-2a464.firebaseapp.com',
    storageBucket: 'shared-notes-app-2a464.firebasestorage.app',
    measurementId: 'G-QM9WRKEQN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ4-FJVtOWw_pTPGA8H1KIfbYU9hNcydo',
    appId: '1:357089760561:android:54a77719ffe99224724c10',
    messagingSenderId: '357089760561',
    projectId: 'shared-notes-app-2a464',
    storageBucket: 'shared-notes-app-2a464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk4Gm9Q-mv7fHxfeakp3SpDsPbP34ZtYI',
    appId: '1:357089760561:ios:e2a3856c082ba37c724c10',
    messagingSenderId: '357089760561',
    projectId: 'shared-notes-app-2a464',
    storageBucket: 'shared-notes-app-2a464.firebasestorage.app',
    iosBundleId: 'com.example.sharedNotesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk4Gm9Q-mv7fHxfeakp3SpDsPbP34ZtYI',
    appId: '1:357089760561:ios:e2a3856c082ba37c724c10',
    messagingSenderId: '357089760561',
    projectId: 'shared-notes-app-2a464',
    storageBucket: 'shared-notes-app-2a464.firebasestorage.app',
    iosBundleId: 'com.example.sharedNotesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgGheHUNRhYJhDOTsgxzzpx-tVlgEDVpc',
    appId: '1:357089760561:web:b1f903bc820113fe724c10',
    messagingSenderId: '357089760561',
    projectId: 'shared-notes-app-2a464',
    authDomain: 'shared-notes-app-2a464.firebaseapp.com',
    storageBucket: 'shared-notes-app-2a464.firebasestorage.app',
    measurementId: 'G-0VGBVY09ZG',
  );
}
